networks:
  laravel_network:
    driver: bridge

services:
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    container_name: backend
    #working_dir: /app
    ports:
      - "8000:8000"  
    networks:
      - laravel_network
    command: [ "sh", "-c", "cp .env.example .env && echo 'DB_DATABASE=database/laravel' >> .env && php artisan key:generate && php artisan config:cache && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=8000" ]


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.angular
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   volumes:
  #     - .:/var/www
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"  
  #   depends_on:
  #     - backend
  #   networks:
  #     - laravel_network

